# Generated by Django 2.1.7 on 2019-03-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190325_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
