# Generated by Django 2.1.7 on 2019-03-25 05:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190325_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview_description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
